# Generated by Django 3.2.9 on 2021-11-26 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "pub_date",
                    models.PositiveIntegerField(
                        blank=True,
                        default=2021,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            book.models.max_value_current_year,
                        ],
                    ),
                ),
                ("isbn", models.CharField(blank=True, max_length=255, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, null=True)),
                (
                    "pub_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.author",
                    ),
                ),
            ],
        ),
    ]
